src/Kdyby/Doctrine/DI/OrmExtension.php
tests/KdybyTests/Doctrine/Extension.phpt
tests/KdybyTests/Doctrine/config/memory.neon
tests/KdybyTests/Doctrine/config/multiple-connections.neon
tests/KdybyTests/nette-reset.neon

I use so many extensions that I want to namespace them:
```
extensions:
kdyby.doctrine: Kdyby\Doctrine\DI\OrmExtension
```
Worked fine with Kdyby/Doctrine 2.1, but doesn't work with 2.2.0.
The exception:
```
Nette\InvalidArgumentException: Missing parameter 'kdyby.doctrine.dbal.defaultConnection'.
(previous) Nette\InvalidArgumentException: Missing item 'kdyby'.
```

Fixed BC break when extension name contains a dot

---

src/Kdyby/Doctrine/Entities/Attributes/Identifier.php

I've found [this topic](https://help.kdyby.org/question/?questionId=441) on Kdyby forum and noticed something. I'm not sure when it chaged but Doctine now generates this code for non-final getId method:
```php
/**
* {@inheritDoc}
*/
public function getId()
{
if ($this->__isInitialized__ === false) {
return (int)  parent::getId();
}
$this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());
return parent::getId();
}
```
It should be ok to remove the final if doctrine behaves this way, right?

Removed final from Identifier::getId()

---

src/Kdyby/Doctrine/EntityRepository.php

I have a query that results in a single scalar. So I need either to add this parameter to the fetch method, or a new method fetchSingleScalar. Not sure which solution would be better, at this moment I favor this one. What do you think?

EntityRepository: fetch with different hydration mode

---

composer.json
src/Kdyby/Doctrine/DI/IRepositoryFactory.php
src/Kdyby/Doctrine/DI/OrmExtension.php
src/Kdyby/Doctrine/RepositoryFactory.php
tests/KdybyTests/Doctrine/RepositoryFactory.phpt
tests/KdybyTests/Doctrine/config/repository-factory.default-class.neon
tests/KdybyTests/Doctrine/config/repository-factory.manual.neon
tests/KdybyTests/Doctrine/config/repository-factory.neon
tests/KdybyTests/Doctrine/config/repository-factory.without-service.neon
tests/KdybyTests/Doctrine/models/cms.php
tests/KdybyTests/Doctrine/models/cms.repositories.php

[Fixes #179]
This got broken with custom RepositoryFactory, that was implemented only half way, I'm sorry about this. The following syntax should be fixed and working fine with this PR.
```yml
services:
-
class: KdybyTests\Doctrine\CmsEmployeeRepository
factory: @Kdyby\Doctrine\EntityManager::getRepository(KdybyTests\Doctrine\CmsEmployee)
-
class: KdybyTests\Doctrine\CmsGroupRepository
factory: @Kdyby\Doctrine\EntityManager::getDao(KdybyTests\Doctrine\CmsGroup)
```
please note that the `getDao` method is deprecated
Often, you might wanna custom repository, without registering it as a service. You can still do that
```php
/**
* @ORM\Entity(repositoryClass="KdybyTests\Doctrine\CmsCommentRepository")
* @ORM\Table(name="cms_comments")
*/
class CmsComment
```
This will work, but as expected, …

RepositoryFactory: implemented handling of repositories as services

---

docs/en/index.md
src/Kdyby/Doctrine/Entities/Attributes/UniversallyUniqueIdentifier.php

Added trait which adds UUID to a Doctrine entity, instead of basic auto incremented numeric id.
See
- https://en.wikipedia.org/wiki/Universally_unique_identifier
- https://www.clever-cloud.com/blog/engineering/2015/05/20/Why-Auto-Increment-Is-A-Terrible-Idea/

Added UniversallyUniqueIdentifier trait

---

src/Kdyby/Doctrine/DI/OrmExtension.php

http://doctrine-orm.readthedocs.org/en/latest/changelog/migration_2_5.html#query-api-add-support-for-default-query-hints

Add configuration for default query hints

---

src/Kdyby/Doctrine/EntityManager.php
src/Kdyby/Doctrine/Tools/NonLockingUniqueInserter.php

The documentation states that ```NonLockingUniqueInserter::persist()``` calls ```$em->flush()``` internally but it should also clearly say that it returns **ANOTHER** instance of the entity class on success (which is obvious because it returns the result of ```$em->merge()``` but you don't know that until you examine the source code).

Warning about the usage of safePersist and NonLockingUniqueInserter

---

src/Kdyby/Doctrine/DI/OrmExtension.php

I was trying to convince  Kdyby/Doctrine to use the default annotation driver from doctrine instead of the kdyby implementation. I tried this configuration:
```
kdyby.doctrine:
metadata:
App: Doctrine\ORM\Mapping\Driver\AnnotationDriver(
reader: @Doctrine\Common\Annotations\Reader
paths: '%appDir%/src/Module/AdminModule'
)
```
Turns out it is currently impossible to use an implementation which is not in `OrmExtension::$metadataDriverClasses`. This PR makes that possible.
Of course in case I've the syntax wrong and it is supposed to be done differently, please tell me.

Allow custom annotation driver class

---

src/Kdyby/Doctrine/QueryObject.php

setMaxResult(1) limits oneToMany/manyToMany associations.

Remove LIMIT 1 for fetchOne

---

src/Kdyby/Doctrine/Tools/CacheCleaner.php

This allows to use other then Kdyby version of EntityManager
Functionality remains the same.

CacheCleaner: release Kdyby lock for EntityManager

---

src/Kdyby/Doctrine/EntityManager.php
src/Kdyby/Doctrine/EntityRepository.php
src/Kdyby/Persistence/Queryable.php

Implementation of QueryExecutor & Queryable interfaces on EntityManager itself to cut the need to use EntityRepositories.
Closes #217

EntityManager: Implement QueryExecutor & Queryable

---

src/Kdyby/Doctrine/DI/OrmExtension.php

If the exception is throwed then "Warning: sprintf(): Too few arguments" is reported. I have tried to fix it by inserting right arguments.

Fix missing arguments

---

src/Kdyby/Doctrine/Entities/Attributes/Identifier.php
src/Kdyby/Doctrine/Entities/Attributes/UniversallyUniqueIdentifier.php

Some people (me including) may use these traits without MagicAccessors trait and then IDE suggests id property, which will produce error.
These annotations can be be easily written to entity class (since you are writing them anyway, when using magic accessors, if you want your IDE to suggest parameters)

Remove @property-read from attribute traits

---

src/Kdyby/Doctrine/Entities/MagicAccessors.php

The `__construct` method in MagicAccessors Trait is empty and causes problems with others Traits defining a constructor.
Closes #254

MagicAccessors: empty ::__construct removed [Closes #254]

---

tests/KdybyTests/Doctrine/Console/CommandTestCase.php
tests/KdybyTests/Doctrine/Extension.phpt
tests/KdybyTests/Doctrine/ORMTestCase.php
tests/KdybyTests/Doctrine/RepositoryFactory.phpt
tests/KdybyTests/Doctrine/proxies-sessions-test/run.php
tests/KdybyTests/nette-reset.neon

Some tests are currently failing with Nette 2.4 because of this error:
```
Exited with error code 255 (expected 0)
E_USER_DEPRECATED: Sections in config file are deprecated.
```

Tests: Remove configuration sections

---

docs/en/repository.md

I get this wrong from time to time and I always have to re-learn what the hell is going on in [QueryBuilder::whereCriteria()](https://github.com/Kdyby/Doctrine/blob/master/src/Kdyby/Doctrine/QueryBuilder.php#L45).
I thought it would be nice to have a simple overview of the syntax, so I added it to the documentation.

Added more examples of EntityRepository::findBy() operators

---

src/Kdyby/Doctrine/QueryObject.php

Function `QueryObject::count` should always return integer, because `ResultSet::getTotalCount` expects (and also should return) integer. At this moment `getSingleScalarResult` may return `"0"` and this means that function `ResultSet::isEmpty` returns `false` (but should return `true`).

QueryObject::count returns always integer

---

src/Kdyby/Doctrine/Geo/Element.php
tests/KdybyTests/Doctrine/Geo/Element.phpt

The original one-pass regexp fails with "Failed due to limited JIT stack space (pattern: ~^(?P<name>\w+)\(\(?(?P<coords>(?:[\d\.]+\s* \s*[\d\.]+)(?:\s*,\s*[\d\.]+\s* \s*[\d\.]+)*)\)?\)$~i)".
Alternative one-letter solution that uses ungreedy modifier only postpones the problem to longer strings.

Geo\Element: fixed validation for long geo-strings

---

src/Kdyby/Doctrine/DI/OrmExtension.php
tests/KdybyTests/Doctrine/config/proxiesSessionAutoloading.neon
tests/KdybyTests/nette-reset.neon

Bug fix: yes
Previous version did not depend on name of annotation extension. After #311 Kdyby/Doctrine search for extension with name 'annotations'.
It is not compatible with following extension configuration:
```yml
extensions:
kdyby.events: Kdyby\Events\DI\EventsExtension
kdyby.annotations: Kdyby\Annotations\DI\AnnotationsExtension
kdyby.doctrine: Kdyby\Doctrine\DI\OrmExtension
```

Add auto search for annotation extension name

---

src/Kdyby/Doctrine/DI/OrmExtension.php
tests/KdybyTests/Doctrine/config/metadata-empty.neon

Bugfix: yes
After PR #311 there is problem with empty config metadata e.g.:
```yaml
doctrine:
metadata: [] # empty or missing
```

Fix empty metadata (annotation driver)

---

src/Kdyby/Doctrine/Geo/Element.php

Dobrý den :)
při používání knihovny jsme narazili na zajímavou věc, nelze používat geo/Element se zápornými souřadnicemi :) (cokoliv od Greenwich na západ a od rovníku dolů. :) )
Tohle nám to opravilo, tak snad nebudete proti. :)

fixing negative coordinates
